### ISSUE TITLE
Hardwareacceleration?

### ISSUE THREAD

**Issue by DerP4si** [Krutyi-4el/DandelionMusic#13]
Hey idk if thats possible, but i am using the bot in a simple python docker on my nas. If i add bigger playlists (55songs+) it often happens that the bot is crashing. My question is now if its somehow possible to use hardware exceleration for the transcoding. In jellyfin f.e it works via a [DEVICE ](https://www.reddit.com/r/jellyfin/comments/exepia/comment/iz6cv8o/?utm_source=share&utm_medium=web2x&context=3)variable. But thats just a thought that i just had...

**Comment by Krutyi-4el** [comment]
I don't think that it is related to the issue. How exactly is it crashing? Can you give an example of playlist that causes this?

**Comment by DerP4si** [comment]
no theres no specific playlist causing it... it just happens from time to time... might be caused by my way of using docker... Ah thats what i wanted to ask: why don't upload the dockerimage to [dockerhub](https://registry.hub.docker.com/)? Many people re looking there for dockercapable bots and so on (f.e. all synology NAS's). Would be awesome to just load the newest image and done ☺

**Comment by Krutyi-4el** [comment]
I'll appreciate if you can gather more information on this.
Honestly, I have a little experience with docker. Thanks for suggesting uploading it, I'll try to post it there.

**Comment by DerP4si** [comment]
"Honestly, I have a little experience with docker." yip... same 👀 Almost just know how to start and stop a container ^^ I don't even know how to use the dockerfile... but i got a Synology NAS in witch docker has a ui and downloads images from dockerhub ^^
