### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [Krutyi-4el/DandelionMusic#171]
WARNING: [youtube] 4qvtFKkWwXU: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 34nlrXcG4fprIYWzE ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] 4qvtFKkWwXU: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 5jEisqFgAhoyoHnqS ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
[tls @ 0000028f015e4100] Error in the pull function.
[tls @ 0000028f015e4100] IO error: Error number -10054 occurred
WARNING: [youtube] vUvuZdSnvYM: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 4DByDPfUNNibNUgiZ ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] vUvuZdSnvYM: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = T_JxLN9s41vtq1oR3 ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] -fWDC2mP_VA: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 5gwUdasdPspxW4Nhc ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] -fWDC2mP_VA: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = _AImODrLW-cACoKkm ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] vUvuZdSnvYM: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = qrRclSFGN59dGiyVS ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] vUvuZdSnvYM: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = vSsf1tYXoJCr9ae1D ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] 4qvtFKkWwXU: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = Hz3GhKBWi17UDniDr ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
[tls @ 0000016dc8665100] Error in the pull function.
[tls @ 0000016dc8665100] IO error: Error number -10054 occurred
[tls @ 0000016dc8c70b40] Error in the pull function.
[tls @ 0000016dc8c70b40] IO error: Error number -10054 occurred
[tls @ 0000016dc8db9fc0] Error in the pull function.
[tls @ 0000016dc8db9fc0] IO error: Error number -10054 occurred
[tls @ 0000016dc866d640] Error in the pull function.
[tls @ 0000016dc866d640] IO error: Error number -10054 occurred
WARNING: [youtube] Cgz03giKzsc: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 4-eiN-fqzACfdAF3K ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
[tls @ 0000018a81d7ef00] Error in the pull function.
[tls @ 0000018a81d7ef00] IO error: Error number -10054 occurred
[tls @ 0000018a821f0240] Error in the pull function.
[tls @ 0000018a821f0240] IO error: Error number -10054 occurred
[tls @ 0000018a82299780] Error in the pull function.
[tls @ 0000018a82299780] IO error: Error number -10054 occurred
WARNING: [youtube] t5ELcMfL7sI: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = _wPZWx_qhMp9w4EOC ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] t5ELcMfL7sI: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = jsK_GIAt7VTOXJlOv ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
[tls @ 000001d02711a580] Error in the pull function.
[tls @ 000001d02711a580] IO error: Error number -10054 occurred
[tls @ 000001d0276fef00] Error in the pull function.
[tls @ 000001d0276fef00] IO error: Error number -10054 occurred
[tls @ 000001d027115e00] Error in the pull function.
[tls @ 000001d027115e00] IO error: Error number -10054 occurred
[tls @ 000001d0276fef00] Error in the pull function.
[tls @ 000001d0276fef00] IO error: Error number -10054 occurred
[tls @ 000001d02776a780] Error in the pull function.
[tls @ 000001d02776a780] IO error: Error number -10054 occurred
WARNING: [youtube] cb4gBO4TjSI: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = H2s_8SX8PCnuAGkFX ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] cb4gBO4TjSI: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = nkjfI-CbtfiWufFR7 ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
WARNING: [youtube] djeM-0EHv9I: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 4XiaqRH0Y9dnMMBCT ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
[tls @ 0000018e7b914100] Error in the pull function.
[tls @ 0000018e7b914100] IO error: Error number -10054 occurred
[tls @ 0000018e7b91aec0] Error in the pull function.
[tls @ 0000018e7b91aec0] IO error: Error number -10054 occurred

**Comment by solaluset** [comment]
What exactly happens? Does the bot play music?
If it does, you can ignore those errors. If not, please provide me:
- The link you're trying to play
- OS you're using
- Whether you use Spotify API or custom cookies
