### ISSUE TITLE
Dandelionmusic is now on dockerhub!

### ISSUE THREAD

**Issue by DerP4si** [Krutyi-4el/DandelionMusic#18]
https://hub.docker.com/r/derpasi/dandelionmusicbot

I am looking forward to improvement suggestions.

**Comment by DerP4si** [comment]
I would add the dockerstuff, yes i think... As for the upload quesion: i don't know ^^ I am going to do it after every "major" update, simply cause i use it myself.
Please tell me if you think the readme has to get changed...

**Comment by Krutyi-4el** [comment]
I've set up an action that will build and upload image automatically when `master` branch gets updated.

**Comment by DerP4si** [comment]
Yes just saw it 👍 nice
