### ISSUE TITLE
Error after adding a Playlist

### ISSUE THREAD

**Issue by DerP4si** [Krutyi-4el/DandelionMusic#23]
If i add a playlist 10< the bot crashes with:

![image](https://user-images.githubusercontent.com/28807283/213936134-3d815af1-e4fc-4883-9433-06ba14293206.png)

after this crash its not able to play any song until restart.

this is a example playlist:
https://open.spotify.com/playlist/3coBvt680BYmNXVr1roQve?si=f7991edc79a74bec

**Comment by DerP4si** [comment]
huh weird, Yes i do...
Ok... if i load [this playlist](https://open.spotify.com/playlist/37i9dQZF1DX5wDmLW735Yd?si=d1b551d0f3b84597) first and add the [playlist above](https://open.spotify.com/playlist/3coBvt680BYmNXVr1roQve?si=f7991edc79a74bec) then theres no error... Do you think i should try new spotify-creds ?

**Comment by Krutyi-4el** [comment]
No, I don't think it is related to how the songs are loaded. Actually, it looks like an error in Pycord itself. Are all the requirements same as specified in `requirements.txt`?

**Comment by DerP4si** [comment]
should be... it's the docker version 🤷‍♂️... but i had this error on my pc too.

**Comment by Krutyi-4el** [comment]
Maybe. I'm not messing with `executable` argument, so it should use default value. Tell me if you find a way to reproduce it. Or should I just play your playlist several times?

**Comment by DerP4si** [comment]
Reinstalled the Docker... thems to work again... no clue why it didn't before 🤷‍♂️ 
*theres still a bug with disappearing buttons if pressing the shuffle button and then the skip button

**Comment by DerP4si** [comment]
ahh could it  be that the bot gets confused by instant disconnecting it without issuing the stop command before ?

**Comment by Krutyi-4el** [comment]
I've tried again and it got thrown

**Comment by DerP4si** [comment]
> I've tried again and it got thrown

yep i got it there too by now ^^

**Comment by Krutyi-4el** [comment]
Seems like when there are too many requests to YouTube, it refuses to provide necessary data. I've attempted to fix it in the `develop` branch, can you try it out?

**Comment by DerP4si** [comment]
Yayy - at least for now it seems to work just fin 🙌 thx! And thx for ur incredible quick responses and fixes! 🤝

**Comment by DerP4si** [comment]
Yayy - at least for now it seems to work just fin 🙌 thx! And thx for ur incredible quick responses and fixes! 🤝
