### ISSUE TITLE
Bot tries to download then breaks on unavailable video

### ISSUE THREAD

**Issue by ANintendoIdiot** [Krutyi-4el/DandelionMusic#24]
i've been having this problem for many many months now across many updates and can't come across any solution when researching and tinkering with the code myself.

the most common reason for this error seems to be that a video is too long or is unavailable (deleted/private/other). **_it's recognizing that the video is unavailable, but continues trying to download it instead of removing or skipping over it._** my thought was that some type of error handler or filter for these types of videos could help, but i'm not sure where it would go in the code. 

This is an excerpt from one of my error logs: [VideoUnavailable-log.txt](https://github.com/Krutyi-4el/DandelionMusic/files/10503714/VideoUnavailable-log.txt). I used this playlist specifically because I know it has an unavailable video in it.

[as a sidenote, i've been trying to figure out where the options for yt-dl in the source for this are but haven't been able to find them. there's an option for something similar to this, but I forgot what and don't think it would help anyways.]

**Comment by ANintendoIdiot** [comment]
the only current fix i have been able to find for this currently is going back to the previous song and removing the broken song (or clearing the queue), but a problem like this isn't ideal regardless

**Comment by Krutyi-4el** [comment]
Initial attempt to fix this was made in `develop` branch. You can check it out.

**Comment by ANintendoIdiot** [comment]
strange, this seems to work sometimes? when adding a playlist with an unavailable video in it _without_ anything beforehand, the bot simply refuses to play _anything_.
````
WARNING: [youtube:tab] YouTube said: INFO - 1 unavailable video is hidden
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos will be hidden during playback
Ignoring exception in command play:
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 184, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/USER/DandelionMusic-master/musicbot/commands/music.py", line 43, in _play_song
    song = await audiocontroller.process_song(track)
  File "/home/USER/DandelionMusic-master/musicbot/audiocontroller.py", line 351, in process_song
    await self.play_song(self.playlist.playque[0])
  File "/home/USER/DandelionMusic-master/musicbot/audiocontroller.py", line 319, in play_song
    self.guild.voice_client.play(
AttributeError: 'NoneType' object has no attribute 'play'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 344, in invoke
    await ctx.command.invoke(ctx)
  File "/home/USER/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 951, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/USER/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 193, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'play'
ERROR: [youtube] 9Gj47G2e1Jc: Video unavailable. This video is no longer available due to a copyright claim by 一般社団法人日本レコード協会
ERROR: [youtube] 9Gj47G2e1Jc: Video unavailable. This video is no longer available due to a copyright claim by 一般社団法人日本レコード協会
WARNING: [youtube] Signature extraction failed: Some formats may be missing

Ignoring exception in command clear:
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 184, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/USER/DandelionMusic-master/musicbot/commands/music.py", line 227, in _clear
    ctx.guild.voice_client.stop()
AttributeError: 'NoneType' object has no attribute 'stop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 344, in invoke
    await ctx.command.invoke(ctx)
  File "/home/USER/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 951, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/USER/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 193, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'stop'
`
no commands relating to audio or playback will have an effect on the bot.
**but** if there were videos added already (either in the current or a previous session), and then an unavailable video is added afterwards, the unavailable video in the playlist is simply skipped over as intended. also, it seems that "Private video" is an exception string that should be caught as well

**Comment by DerP4si** [comment]
Yep, i had the same behavior in my issue... as soon as there is something in queue it plays evereything just fine... have to test the new dev-version tho...

**Comment by Krutyi-4el** [comment]
> when adding a playlist with an unavailable video in it without anything beforehand, the bot simply refuses to play anything.

Can't reproduce. Do you have an example of playlist that causes this?

**Comment by ANintendoIdiot** [comment]
i had the wrong version of one of the dependencies without realizing, it works correct now (plus the auto-remove feature is excellent)
thank you so so much

**Comment by Krutyi-4el** [comment]
Nice. I'm going to make some more changes and then merge it.
