### ISSUE TITLE
Adding a check for button callbacks

### ISSUE THREAD

**Issue by CrystalMooon** [Krutyi-4el/DandelionMusic#31]
Hello, not much of an issue but more like a feature request.

Could it be possible to add some form of check on playback button presses so that they only work if the user is connected to the same voice channel as the bot is currently on?
As of now the buttons do their function even if pressed by someone who is not connected to any voice channel which can become an issue on less moderated servers.

Thank you for your work.

**Comment by Krutyi-4el** [comment]
Hi. This is very nice thought actually, I somehow forgot about it 😅
