### ISSUE TITLE
Doesn't find Sub-ID -> won't start docker

### ISSUE THREAD

**Issue by DerP4si** [Krutyi-4el/DandelionMusic#41]
![image](https://user-images.githubusercontent.com/28807283/233429788-87a3f7a6-1623-4080-ab46-1928f1e96dfe.png)
 that's the errorcode i get

**Comment by Krutyi-4el** [comment]
Well, have you tried setting `DATABASE_URL`? Or removing it from env?

**Comment by DerP4si** [comment]
Sorry you're right... Didn't Set the env.
