### ISSUE TITLE
The queue button doesnt work

### ISSUE THREAD

**Issue by StonebanksYT** [Krutyi-4el/DandelionMusic#45]
when i press the queue button i get an error in html format : 
Ignoring exception in view <View timeout=None children=10> for item <MusicButton style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='📜' id=None> row=1>:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/ui/view.py", line 414, in _scheduled_task
    await item.callback(interaction)
  File "/home/container/musicbot/audiocontroller.py", line 53, in callback
    await res
  File "/home/container/musicbot/audiocontroller.py", line 238, in queue_callback
    await ctx.send(
  File "/home/container/musicbot/bot.py", line 173, in send
    res = await self.respond(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/bridge/context.py", line 93, in respond
    return await self._respond(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/bridge/context.py", line 146, in _respond
    return await self._get_super("respond")(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/context.py", line 286, in respond
    return await self.followup.send(*args, **kwargs)  # self.send_followup
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/webhook/async_.py", line 1745, in send
    data = await adapter.execute_webhook(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/webhook/async_.py", line 198, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): <!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>

</script>
<script>(function(){var js = "window['__CF$cv$params']={r:'7d404e615d874172',m:'ypjoy3c68GKMmG5NqSwGab0iUfd83ytNqezzkxVxQ8U-1686218619-0-AYpY58ZY/PPZ6ko6DFT3Z8sdD0vN43D+W5rD4lgK+EsW'};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/invisible.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body>
</html>
The CD emoji button doesnt work either. The play pause shuffle skip loop stop work fine

**Comment by Krutyi-4el** [comment]
Can you try it again after some time? How many servers is the bot on? Are there any other problems or information in the console?
Also, you should remove your IP from the issue

**Comment by StonebanksYT** [comment]
I am running it on Bot Hosting website called Daki. The server is in Germany.

**Comment by Krutyi-4el** [comment]
Got it. Looks like this hosting is free, which means that there may be a lot of bots running on shared IPs and trigger rate limits. Using proxy server may solve this issue, check out `proxy-test` branch and let me know how it goes.
