### ISSUE TITLE
Spotify links do not work

### ISSUE THREAD

**Issue by DerP4si** [Krutyi-4el/DandelionMusic#46]
Hi,
when i try to play
[An age restricted song](https://open.spotify.com/intl-de/track/5pdJF1llUVwpJdhTx4BUOy?si=c95ccbbefe35467b)
this errormessage appears

```
Error: Unsupported site or age restricted content. To enable age restricted content check the documentation/wiki.
```

My question is now wich cookies from wich site are needed? I tried to use my spotify cookies but that didnt help...
I exported them using "Get cookies.txt LOCALLY".

**Comment by DerP4si** [comment]
Hmm... Do I have to activate the feature specifically?
I tried it with my cookies and it doesn't work… But I don't know if it's just too long ago that saw a mature content video…  and I didn't found one by search yesterday ^^

**Comment by DerP4si** [comment]
I just found out that it isn't the age restriction but the fact that the links that I use are from Spotify. So the error message appears every time that i paste a Spotify link…

**Comment by Krutyi-4el** [comment]
You are right. Looks like Spotify changed link formats, I'll investigate it

**Comment by Krutyi-4el** [comment]
Can you please post here more examples of the Spotify links? I don't use Spotify so this isn't easy for me 😅

**Comment by DerP4si** [comment]
sure <3
https://open.spotify.com/intl-de/track/1x9n7E0HHf0bdw2wiAqvsc?si=54301574031348f5
https://open.spotify.com/intl-de/track/6yZyQ2sDmelY3C6KesOYYL?si=4c96a3e319fd46e9

**Comment by Krutyi-4el** [comment]
Do you have an idea what does `intl-de` mean? Looks like it isn't a constant, is it localisation code? 🤔

**Comment by DerP4si** [comment]
hmm jip its localisation... if you type 
https://open.spotify.com/intl-us/track/1x9n7E0HHf0bdw2wiAqvsc?si=54301574031348f5
it redirects to `intl-de` at least in my case... This happens even with vpn in a incognito window...

**Comment by Krutyi-4el** [comment]
Thanks, I'll make a regex then

**Comment by Krutyi-4el** [comment]
Btw, what about playlists?

**Comment by DerP4si** [comment]
Playlists work as usual✌️

**Comment by Krutyi-4el** [comment]
^ awaiting your approval @DerP4si :)

**Comment by DerP4si** [comment]
Sorry, i try to test it but:

```
Processing ./config
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 17, in <module>
          from config.config import DATABASE_LIBRARY
        File "/root/DandelionMusic-fix-spotify/config/./config.py", line 6, in <module>
          from config.utils import get_env_var, alchemize_url
      ModuleNotFoundError: No module named 'config.utils'; 'config' is not a package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by Krutyi-4el** [comment]
Try with a fresh venv and the newest version of pip

**Comment by DerP4si** [comment]
Yeah i got it to work on windows... I tried to start it on an ubuntu-vm before... I have no clue why that didn't work but anywho…. I reviewed it and it works 😎…  I think I approved it but I'm just not often enough on github so it could be that I have to do something else ^^

**Comment by Krutyi-4el** [comment]
Thanks!
> I have no clue why that didn't work

I'll remake that part in 1.6, it always led to weird behaviour 😅

**Comment by DerP4si** [comment]
I have to test it but could it be that changing the config file before installing the requirements.txt Is leading to some installing issue? Just a thought that I had because on the Ubuntu machine I tried to fill in the right config stuff before installing the req. and now I first installed the req’s and it was successful🤔😅

**Comment by Krutyi-4el** [comment]
No, I don't think it's the cause. `setup.py` is pure black magic rn 😆. But at least it worked. Anyway, I've already rewritten some parts in `format` branch, I hope it'll fix `config.utils` issue for ever.

**Comment by DerP4si** [comment]
😂😂 ok
i'm exited for the next master merge to get the updated docker ^^

**Comment by DerP4si** [comment]
Addition:
Albumlinks aren't working either 👀🤔😄
https://open.spotify.com/intl-de/track/0tJttQ1r0KBjnxarI5mDrs?si=1ff708f28e954bcc
playlists are ok tho.
