### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by dabmaster40** [Krutyi-4el/DandelionMusic#5]
Would you ever make the music commands use slash command inputs? I remember asking Raptor this a lot but sadly IDK if he's working on DingoLingo anymore. :/

**Comment by Krutyi-4el** [comment]
I've thought about this too, but it's quite a big change afterall. I plan to give it a try though.

**Comment by Krutyi-4el** [comment]
I'm working on this in `develop` branch, you're free to test it and give suggestions/improvements.

**Comment by Krutyi-4el** [comment]
Changes were merged to `master`.
