### ISSUE TITLE
After running the play command, the bot simply duplicates itself and doesn't play

### ISSUE THREAD

**Issue by rmarinic** [Krutyi-4el/DandelionMusic#55]
Managed to connect the bot with the token, successfully in the server. Running help/settings command work normally, but after trying to play a song, the bot starts again and nothing happens and now there are 2 bots running which will result in duplicate actions after typing the help command or such.

After trying to run play again when 2 or more bots are running this error pops out directly into discord chat by the bot itself: 
```
Command raised an exception: RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if name == 'main':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
        
I'm not sure what I'm doing wrong, seems like I setup everything correctly but I must have missed something, can't seem to find the reason why the bot just runs twice instead of playing the music.

**Comment by Krutyi-4el** [comment]
Do you use the `exe` file?

**Comment by rmarinic** [comment]
No, I am running the run.py file. Sorry for not mentioning it.

**Comment by Krutyi-4el** [comment]
You are on windows, right?

**Comment by rmarinic** [comment]
Yes.

**Comment by rmarinic** [comment]
![image](https://github.com/Krutyi-4el/DandelionMusic/assets/42251018/c6f9a25f-6155-4990-be7c-44c2bc48fc32)

Example of what happens in the terminal after writing the play command in discord. (PID gets printed out followed by the bot starting itself again)

**Comment by rmarinic** [comment]
Just to give you an update, using the code from the #56 everything works perfectly fine now. Thanks for the quick help!
