### ISSUE TITLE
Spotify links do not work (Albums)

### ISSUE THREAD

**Issue by DerP4si** [Krutyi-4el/DandelionMusic#60]
Addition to #46 :
Albumlinks aren't working either 👀🤔😄
https://open.spotify.com/intl-de/track/0tJttQ1r0KBjnxarI5mDrs?si=1ff708f28e954bcc
playlists are ok tho.

**Comment by Krutyi-4el** [comment]
The link you've provided looks like a track link and it works

**Comment by DerP4si** [comment]
Yep... sry, here's the albumlink:
https://open.spotify.com/intl-de/album/5WEe6GjK467yw02jAlz9lb?si=JUgMpL7FT8W3tziXeJZwXQ

**Comment by DerP4si** [comment]
works 🥳🥰
