### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by PhoenixOrigin** [Krutyi-4el/DandelionMusic#7]
Config doesn't work. I have downloaded requirements.txt and ran it using pip but anything related to dirs doesnt work; from musicbot.bot etc nothing works. Majorly from config import config doesnt work

**Comment by Krutyi-4el** [comment]
How are you running the bot? Also, full error messages are greatly appreciated.

**Comment by PhoenixOrigin** [comment]
Sorry I'm dumb I fixed I was running the wrong file xd
