### ISSUE TITLE
Looped song stops playing when URL expires

### ISSUE THREAD

**Issue by Krutyi-4el** [Krutyi-4el/DandelionMusic#75]
When a song played from YouTube stays in cache for a long time, its URL expires and attempting to play it will produce the error:

```
[https @ 0x55b83548e740] HTTP error 403 Forbidden
<long raw URL here>: Server returned 403 Forbidden (access denied)
```

## To reproduce

Make a song play on loop and wait several hours until URL expires and stops playing.

## Possible solution

Check the `error` argument of `next_song` (and refresh the URL if needed):

https://github.com/Krutyi-4el/DandelionMusic/blob/94534434aaccde216df00fa636b9bf42e2980816/musicbot/audiocontroller.py#L271

**Comment by Krutyi-4el** [comment]
Thanks @SenninMoodo for the report btw 😅

**Comment by SenninMoodo** [comment]
> Thanks @SenninMoodo for the report btw 😅

Welcome.
So from user-side there is no workaround atm? I guess you'll release a new version when fixed?

**Comment by Krutyi-4el** [comment]
Yeah, I'm already working on this

**Comment by SenninMoodo** [comment]
> Yeah, I'm already working on this

Is there a way to play local files as well? Just saw the supported extensions in the config.json and was wondering if this is a feature that is just not listed?

**Comment by Krutyi-4el** [comment]
That's for custom files in raw form, like https://cdn.discordapp.com/attachments/821490919068139582/1174766666845003866/my_cool_audio.mp3

Technically you can play files that are on the same host as bot if you run a web server (`python -m http.server` is the simplest example).

**Comment by SenninMoodo** [comment]
> That's for custom files in raw form, like https://cdn.discordapp.com/attachments/821490919068139582/1174766666845003866/my_cool_audio.mp3
> 
> Technically you can play files that are on the same host as bot if you run a web server (`python -m http.server` is the simplest example).

I tried that method but I guess I'm missing something. How exactly can I access the local files via bot? Did bind the http server to localhost and thought "d!p localhost:<port>/file.mp3" should do the trick, but as it seems this won't send a GET to the server. 

Besides is there a way to get a file into discords cdn except with sending it someone?
