### ISSUE TITLE
Player buttons

### ISSUE THREAD

**Issue by DerP4si** [Krutyi-4el/DandelionMusic#9]
this is an enhancement.

Hi thx for keeping Dingolingo alive <3

I tested around with discord.ui elements, cause its way more convenient than always typing ^^

this is the current result:
![image](https://user-images.githubusercontent.com/28807283/209659976-2c9698be-7e2b-4b42-a885-40aadc121d5d.png)

it pops up automaticly after executing the play command and regenerating itself after using any button so it always is the last thing typed.
![image](https://user-images.githubusercontent.com/28807283/209660691-fda8dc24-8fcb-4e37-a248-29ae24535fe7.png)

If using the "stop" button it disconnects and deleting the controller entirely. 
![image](https://user-images.githubusercontent.com/28807283/209660751-2fff7904-f322-4ca5-b4ae-8dae136962b5.png)

At the moment it isn't deleted if the bot disconnects after 600s.
In addition if using the play command again the controller gets generated again. (thats ezz to fix but i have to figure out how i want to do it)
![image](https://user-images.githubusercontent.com/28807283/209661303-6fd5bf86-be5f-4fbc-97bf-1015c6fb0ae3.png)

try it urself ^^ i just added it to the music.py... (should work)

[music.zip](https://github.com/Krutyi-4el/DandelionMusic/files/10307917/music.zip)

**Comment by Krutyi-4el** [comment]
Thanks for your input as well! I think this is a good addition. What do you think about creating pull request via GitHub to be listed as a contributor?

**Comment by DerP4si** [comment]
Sounds cool but i have no clue of anykind from git and how to work with it's features... (branches somewhat but the rest is unknown to me). Also i think the code has room for improvement, cause i just somehow wanted to get it to work and didn't followed any "code design" rules ^^

**Comment by DerP4si** [comment]
oops didn't want to close it, lol... as i said unknown to me 😂

**Comment by Krutyi-4el** [comment]
So, should I wait until you improve it?

**Comment by DerP4si** [comment]
No, it works as far as i know good (pls test it, there're gonna be bugs for sure) ... I don't know how to delete the interaction.message if disconnect by timeout... You are more into that code and can properly figure out a solution for that faster than i could. I also don't know how to properly make it that the interaction.message rebuilts after executing another play command so that there's always just one controller... All i do is throw some code together that might or might not work and test different adjustments until it's working ^^ I just don't know enough about python yet... 
Oh another info: the aiohttp 3.8.1 doesn't work with py 3.11 i didn't tested other versions than 3.9 because in 3.9 it works fine... that was a rime... haha

**Comment by Krutyi-4el** [comment]
Ok! I'll apply your changes when I have time, then.

**Comment by DerP4si** [comment]
i now forked [DandelionMusic](https://github.com/Krutyi-4el/DandelionMusic/) myself and added all changes to the test branch. I'm still fighting with the delete process of the old controller when a new controller is generated by !dplay (url). + i don't know how to delete it after auto disconnect either ^^

**Comment by Krutyi-4el** [comment]
I think the controller (or the message with it) can be stored in audiocontroller. Sorry for not being able to test/review it at the moment. You can create a draft pull request though.

**Comment by Krutyi-4el** [comment]
I've started working on my own implementation in `develop` branch. You can let me know your thoughts on it.

**Comment by DerP4si** [comment]
Awesome.. yeah thats so much smarter than my try 😄 As i said i'm not into that haul "this could be a class and that could be a new object and so on" thinking 😅... Yet (hopefully😂) can't try it right now but it looks pretty promising 👍

**Comment by DerP4si** [comment]
Yip, nice! but i would probably change 2 things:
1. Give the shufflebutton an shuffle-indicater (like the loopbutton f.e) so theres no confusion in a group if the playlist is shuffelt or not...
2. add volume-buttons
but in conclusion this is great so far 😇

**Comment by DerP4si** [comment]
Uuh found a bug:
If you shuffle via button and then skip to the next song the buttons disapear

**Comment by Krutyi-4el** [comment]
1. Playlist cannot be played in random order (at least currently). Shuffling is a one-time action.
2. There are two reasons why I didn't add them. Firstly, I'm going to sacrifice the whole volume feature in favour of speed because I think that everyone uses discord volume controls (don't you? 🤔). Secondly, I see that there are a lot of already existing buttons.
3. The stop button has same behaviour as stop command.
4. I can't reproduce the bug you've mentioned.

**Comment by DerP4si** [comment]
Ah ok, i thought it shuffles the playlist ^^
Fr mostly we do it with the bot-volume cause so its loud for everybody if u want to show a song f.e and quiet if its just playing chill-stuff.
I know, i just said how i made it 😁
It's probably connected to the try of me to simply shuffle a playlist and then skip to the next song... if shuffle doesn't work with playlists yet, thats most likely the issues base.

**Comment by Krutyi-4el** [comment]
> Ah ok, i thought it shuffles the playlist
It does, but it shuffles it "all at once".

**Comment by Krutyi-4el** [comment]
@DerP4si I've added volume buttons and tried to fix the issue with disappearing buttons ^

**Comment by DerP4si** [comment]
yes i saw it... already updated my dockers 🤝👍 huge thx to u and all your support <3
